apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic-kubernetes-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-kubernetes-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: newrelic-kubernetes-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic-kubernetes-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-kubernetes-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: newrelic-kubernetes-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic-kubernetes-operator-secrets-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic-kubernetes-operator-secret-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: newrelic-kubernetes-operator-system