---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: newrelic-kubernetes-operator-manager-role
rules:
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertsapmconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertsapmconditions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertschannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertschannels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertsnrqlconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertsnrqlconditions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - alertspolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - apmalertconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - apmalertconditions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - nrqlalertconditions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - nrqlalertconditions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nr.k8s.newrelic.com
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-kubernetes-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic-kubernetes-operator-secret-reader
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list