---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: newrelic-kubernetes-operator-system/newrelic-kubernetes-operator-serving-cert
  name: newrelic-kubernetes-operator-mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: newrelic-kubernetes-operator-webhook-service
      namespace: newrelic-kubernetes-operator-system
      path: /mutate-nr-k8s-newrelic-com-v1-alertsapmcondition
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  name: malertsapmcondition.kb.io
  rules:
  - apiGroups:
    - nr.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alertsapmconditions
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: newrelic-kubernetes-operator-webhook-service
      namespace: newrelic-kubernetes-operator-system
      path: /mutate-nr-k8s-newrelic-com-v1-alertsnrqlcondition
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  name: malertsnrqlcondition.kb.io
  rules:
  - apiGroups:
    - nr.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alertsnrqlconditions
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: newrelic-kubernetes-operator-webhook-service
      namespace: newrelic-kubernetes-operator-system
      path: /mutate-nr-k8s-newrelic-com-v1-alertspolicy
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  name: malertspolicy.kb.io
  rules:
  - apiGroups:
    - nr.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alertspolicies
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: newrelic-kubernetes-operator-webhook-service
      namespace: newrelic-kubernetes-operator-system
      path: /mutate-nr-k8s-newrelic-com-v1-alertschannel
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  name: malertschannel.kb.io
  rules:
  - apiGroups:
    - nr.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alertschannels
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: newrelic-kubernetes-operator-webhook-service
      namespace: newrelic-kubernetes-operator-system
      path: /mutate-nr-k8s-newrelic-com-v1-apmalertcondition
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  name: mapmalertcondition.kb.io
  rules:
  - apiGroups:
    - nr.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apmalertconditions
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: newrelic-kubernetes-operator-webhook-service
      namespace: newrelic-kubernetes-operator-system
      path: /mutate-nr-k8s-newrelic-com-v1-nrqlalertcondition
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  name: mnrqlalertcondition.kb.io
  rules:
  - apiGroups:
    - nr.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nrqlalertconditions
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: newrelic-kubernetes-operator-webhook-service
      namespace: newrelic-kubernetes-operator-system
      path: /mutate-nr-k8s-newrelic-com-v1-policy
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  name: mpolicy.kb.io
  rules:
  - apiGroups:
    - nr.k8s.newrelic.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policies
  sideEffects: None